name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  riscv-ci:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies and AUR helper
        run: |
          echo "ğŸ”§ Updating system and installing base packages..."
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git wget autoconf automake libtool make python verilator

          # Crear usuario normal (makepkg no debe ejecutarse como root)
          useradd -m builduser
          echo "builduser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

          # Instalar yay (AUR helper)
          sudo -u builduser bash -c "
            cd /home/builduser
            git clone https://aur.archlinux.org/yay.git
            cd yay
            makepkg -si --noconfirm
          "

          verilator --version

      - name: Install RISC-V GCC toolchain (AUR)
        run: |
          sudo -u builduser bash -c "
            yay -S --noconfirm riscv64-unknown-elf-toolchain-bin
          "
          riscv64-unknown-elf-gcc --version

          riscv64-unknown-elf-gcc --version
          whereis riscv64-unknown-elf-gcc

      - name: Build Tartaruga
        run: |
          echo "ğŸ—ï¸ Building Tartaruga with Verilator..."
          make clean && make all

      - name: Build ISA tests
        run: |
          echo "ğŸ§© Building RISC-V ISA tests..."
          cd riscv-tests
          autoconf
          export RISCV=/opt/riscv64-unknown-elf-toolchain/
          ./configure --prefix=$RISCV/target
          make isa

      - name: Run ISA tests
        run: |
          echo "ğŸš€ Running ISA tests..."
          chmod +x run_isa_tests.sh
          chmod +x run_tartaruga.sh
          ./run_isa_tests.sh



