name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  riscv-ci:
    runs-on: ubuntu-latest
    container:
      # Cambia esta lÃ­nea por tu contenedor ya creado
      image: ghcr.io/theofficecat/docker-tartaruga:latest
      options: "--user root"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Tartaruga
        run: |
          echo "ğŸ—ï¸ Building Tartaruga with Verilator..."
          cd $GITHUB_WORKSPACE
          make clean && make all

      - name: Build ISA tests
        run: |
          echo "ğŸ§© Building RISC-V ISA tests..."
          cd $GITHUB_WORKSPACE/riscv-tests
          autoconf
          export RISCV=/opt/riscv64-unknown-elf-toolchain/
          ./configure --prefix=$RISCV/target
          make isa

      - name: Run ISA tests
        run: |
          echo "ğŸš€ Running ISA tests..."
          cd $GITHUB_WORKSPACE
          chmod +x run_isa_tests.sh run_tartaruga.sh
          ./run_isa_tests.sh
